Make use of `go list -f {{.GoVersion}} -m` to fetch the Go version of the module.

diff --git a/.ci/check b/.ci/check
--- a/.ci/check
+++ b/.ci/check
@@ -55,16 +55,12 @@ golint -set_exit_status ${LINT_FOLDERS}
 helm lint "${HELM_CHART_PATH}"
 
 echo "Checking Go version"
-while IFS= read -r line
-do
-  if [[ $line =~ ^go.*$ ]]; then
-    if [[ $line =~ ^go\ [0-9]+\.[0-9]+\.0$ ]]; then
-        # Go version is valid, adheres to x.y.0 version
-        exit 0
-    else
-        echo "Go version is invalid, please adhere to x.y.0 version"
-        echo "See https://github.com/gardener/etcd-backup-restore/pull/801"
-        exit 1
-    fi
-  fi
-done < "go.mod"
+GOVERSION=$(go list -f {{.GoVersion}} -m)
+if [[ $GOVERSION =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
+  # Go version is valid, adheres to x.y.0 version
+  exit 0
+else
+  echo "Go version is invalid, please adhere to x.y.0 version"
+  echo "See https://github.com/gardener/etcd-backup-restore/pull/801"
+  exit 1
+fi
