Enhance the `check` make target to ensure the Go version adheres to `x.y.0`. (#803)

diff --git a/.ci/check b/.ci/check
--- a/.ci/check
+++ b/.ci/check
@@ -53,3 +53,13 @@ golint -set_exit_status ${LINT_FOLDERS}
 
 # Execute lint checks on helm chart.
 helm lint "${HELM_CHART_PATH}"
+
+echo "Checking Go version"
+GOVERSION=$(go list -f {{.GoVersion}} -m)
+if [[ ! $GOVERSION =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
+  echo "Go version is invalid, please adhere to x.y.0 version"
+  echo "See https://github.com/gardener/etcd-backup-restore/pull/801"
+  exit 1
+fi
+
+echo "All checks successful"
